name: Drawer
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build VialToKeymapDrawer
        run: |
          export SAVED_PWD="$PWD"
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install haxe -y
          mkdir ~/haxelib && haxelib setup ~/haxelib
          echo "haxe --version"
          haxe --version
          echo "which neko"
          which neko
          export VTKD="$HOME/.VialToKeymapDrawer"
          git clone --depth=1 https://github.com/YAL-Tools/vial-to-keymap-drawer.git $VTKD
          cd $VTKD
          haxe build-neko.hxml
          cd $SAVED_PWD
          neko $VTKD/bin/VialToKeymapDrawer.n --vil ./Cygnus-Keymap.vil --keyboard 'splitkb/aurora/corne/rev1' --layout 'LAYOUT_split_3x6_3' --layer '0,1,2' --omit-m1 ./Cygnus-Keymap.yml
      - name: Generate SVG
        run: |
          python3 ./process.py
          pipx install keymap-drawer
          keymap -c my_config.yaml draw Cygnus-Keymap-Processed.yml -o my_keymap.svg
          echo "git status"
          git status
      # - name: Generate PNG
      #   run: |
      #     set -x
      #     sudo apt-get install -y libfuse2
      #     wget https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.1-43/ImageMagick-a2d96f4-gcc-x86_64.AppImage
      #     mkdir ~/.magick
      #     mv ImageMagick-a2d96f4-gcc-x86_64.AppImage ~/.magick/magick
      #     chmod a+x ~/.magick/magick
      #     export PATH="$HOME/.magick:$PATH"
      #     echo "which magick"
      #     which magick
      #     echo "magick --version"
      #     magick --version
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(SVG): auto update SVG pictures"
