name: Drawer
on:
  push:
    branches:
      - main
    paths:
      - "Cygnus-Keymap.yml"
      - "my_config.yaml"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SVG
        run: |
          python3 ./process.py
          pipx install keymap-drawer
          keymap -c my_config.yaml draw Cygnus-Keymap-Processed.yml --keys-only -o my_keymap.svg
          keymap -c my_config.yaml draw Cygnus-Keymap-Processed.yml --combos-only -o my_keymap_combos.svg
          echo "git status"
          git status
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(SVG): auto update SVG pictures"
