name: Drawer
on:
  push:
    branches:
      - main
    paths:
      - "Cygnus-Keymap.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install keymap-drawer
          keymap -c my_config.yaml draw Cygnus-Keymap.yml >my_keymap.svg
          echo "git status"
          git status
        
