name: Drawer
on:
  push:
    branches:
      - main
    paths:
      - "Cygnus-Keymap.yml"
      - "my_config.yaml"
      - "settings.json"
      - "process.py"
      - ".github/workflows/drawer.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      # - name: Build VialToKeymapDrawer
      #   run: |
      #     sudo add-apt-repository ppa:haxe/releases -y
      #     sudo apt-get update
      #     sudo apt-get install haxe -y
      #     mkdir ~/haxelib && haxelib setup ~/haxelib
      #     echo "haxe --version"
      #     haxe --version
      #     echo "which neko"
      #     which neko
      - uses: actions/checkout@v4
      - name: Generate SVG
        run: |
          python3 ./process.py
          pipx install keymap-drawer
          keymap -c my_config.yaml draw Cygnus-Keymap-Processed.yml -o my_keymap.svg
          echo "git status"
          git status
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(SVG): auto update SVG pictures"
